/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Conexion.Conexion;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Dimension;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.*;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;



/**
 *
 * @author LENOVO
 */
public class InterInformesNomina extends javax.swing.JInternalFrame {

    String cedula;
    
    public InterInformesNomina() {
        initComponents();
        this.setSize(new Dimension(406, 194));
        this.setTitle("Informe Nomina");
        this.CargarComboEmpleados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_Empleados = new javax.swing.JComboBox<>();
        jButton_Reporte = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Informe de Nomina de Empleado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 360, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre del empleado:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jComboBox_Empleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empleado:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 160, -1));

        jButton_Reporte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Reporte.setText("Generar Reporte");
        jButton_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ReporteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ReporteActionPerformed

    if(jComboBox_Empleados.getSelectedIndex() <= 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un empleado para generar el reporte");
        return;
    }

    String empleadoSeleccionado = jComboBox_Empleados.getSelectedItem().toString();

    Connection cn = null;
    try {
        cn = Conexion.conectar();

        // Consulta info personal
        String sqlEmpleado = "SELECT e.cedula, e.Nombre_completo, e.fecha_ingreso, e.fecha_retiro, e.telefono, " +
                "c.Nombre_cargo, d.Nombre_departamento, t.tipo_contrato " +
                "FROM empleado e " +
                "INNER JOIN cargo c ON e.id_cargo = c.id_cargo " +
                "INNER JOIN departamento d ON e.id_departamento = d.id_departamento " +
                "INNER JOIN tipoContrato t ON e.id_tipoContrato = t.id_tipoContrato " +
                "WHERE e.Nombre_completo = ?";

        PreparedStatement psEmpleado = cn.prepareStatement(sqlEmpleado);
        psEmpleado.setString(1, empleadoSeleccionado);
        ResultSet rsEmpleado = psEmpleado.executeQuery();

        if(!rsEmpleado.next()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró información del empleado");
            return;
        }

        // Datos personales
        String cedula = rsEmpleado.getString("cedula");
        String nombre = rsEmpleado.getString("Nombre_completo");
        String fechaIngreso = rsEmpleado.getString("fecha_ingreso");
        String fechaRetiro = rsEmpleado.getString("fecha_retiro");
        String telefono = rsEmpleado.getString("telefono");
        String cargo = rsEmpleado.getString("Nombre_cargo");
        String departamento = rsEmpleado.getString("Nombre_departamento");
        String tipoContrato = rsEmpleado.getString("tipo_contrato");

        // Consulta info bancaria
        String sqlBanco = "SELECT Nombre_banco, Tipo_cuenta, Numero_de_cuenta FROM banco WHERE id_cedula = ?";
        PreparedStatement psBanco = cn.prepareStatement(sqlBanco);
        psBanco.setString(1, cedula);
        ResultSet rsBanco = psBanco.executeQuery();

        String nombreBanco = "No registrado";
        String tipoCuenta = "No registrado";
        String numeroCuenta = "No registrado";

        if(rsBanco.next()) {
            nombreBanco = rsBanco.getString("Nombre_banco");
            tipoCuenta = rsBanco.getString("Tipo_cuenta");
            numeroCuenta = rsBanco.getString("Numero_de_cuenta");
        }

        // Consulta devengados
        String sqlDevengados = "SELECT salario, Sub_transporte, Gastos_representativos, Viaticos, Comisiones, " +
                "Horas_extra_diurnas, Horas_extra_nocturnas, Horas_extra_dominicales_diurnas, Horas_extra_dominicales_nocturnas " +
                "FROM devengados WHERE id_empleado = ?";
        PreparedStatement psDevengados = cn.prepareStatement(sqlDevengados);
        psDevengados.setString(1, cedula);
        ResultSet rsDevengados = psDevengados.executeQuery();

        long salario = 0, subTransporte = 0, gastosRepresentativos = 0, viaticos = 0, comisiones = 0,
                horasExtraDiurnas = 0, horasExtraNocturnas = 0, horasExtraDomDiurnas = 0, horasExtraDomNocturnas = 0;

        if(rsDevengados.next()) {
            salario = rsDevengados.getLong("salario");
            subTransporte = rsDevengados.getLong("Sub_transporte");
            gastosRepresentativos = rsDevengados.getLong("Gastos_representativos");
            viaticos = rsDevengados.getLong("Viaticos");
            comisiones = rsDevengados.getLong("Comisiones");
            horasExtraDiurnas = rsDevengados.getLong("Horas_extra_diurnas");
            horasExtraNocturnas = rsDevengados.getLong("Horas_extra_nocturnas");
            horasExtraDomDiurnas = rsDevengados.getLong("Horas_extra_dominicales_diurnas");
            horasExtraDomNocturnas = rsDevengados.getLong("Horas_extra_dominicales_nocturnas");
        }

        // Consulta descuentos
        String sqlDescuentos = "SELECT salud, pension, credito_empleado FROM descuentos WHERE id_empleado = ?";
        PreparedStatement psDescuentos = cn.prepareStatement(sqlDescuentos);
        psDescuentos.setString(1, cedula);
        ResultSet rsDescuentos = psDescuentos.executeQuery();

        long salud = 0, pension = 0, creditoEmpleado = 0;
        if(rsDescuentos.next()) {
            salud = rsDescuentos.getLong("salud");
            pension = rsDescuentos.getLong("pension");
            creditoEmpleado = rsDescuentos.getLong("credito_empleado");
        }

        // Consulta pagos
        String sqlPagos = "SELECT total_devengados, total_descuentos, total_pago, fecha_pago FROM pagos WHERE id_empleado = ? ORDER BY fecha_pago DESC LIMIT 1";
        PreparedStatement psPagos = cn.prepareStatement(sqlPagos);
        psPagos.setString(1, cedula);
        ResultSet rsPagos = psPagos.executeQuery();

        long totalDevengados = 0, totalDescuentos = 0, totalPago = 0;
        String fechaPago = "No registrado";

        if(rsPagos.next()) {
            totalDevengados = rsPagos.getLong("total_devengados");
            totalDescuentos = rsPagos.getLong("total_descuentos");
            totalPago = rsPagos.getLong("total_pago");
            fechaPago = rsPagos.getString("fecha_pago");
        }

        // Crear documento PDF
        Document document = new Document();
        String rutaEscritorio = System.getProperty("user.home") + "/Desktop/";
        String nombreArchivo = rutaEscritorio + "ReporteNomina_" + nombre.replaceAll(" ", "_") + ".pdf";
        PdfWriter.getInstance(document, new FileOutputStream(nombreArchivo));

        document.open();

        com.itextpdf.text.Font titulo = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 18, com.itextpdf.text.Font.BOLD);
        com.itextpdf.text.Font subTitulo = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 14, com.itextpdf.text.Font.BOLD);
        com.itextpdf.text.Font textoNormal = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 12);

        document.add(new Paragraph("Informe de Nómina del Empleado", titulo));
        document.add(new Paragraph(" "));

        // Tabla datos personales
        PdfPTable tablaPersonal = new PdfPTable(2);
        tablaPersonal.setWidthPercentage(100);
        tablaPersonal.addCell(new PdfPCell(new Phrase("Campo", subTitulo)));
        tablaPersonal.addCell(new PdfPCell(new Phrase("Información", subTitulo)));

        tablaPersonal.addCell("Cédula");
        tablaPersonal.addCell(cedula);

        tablaPersonal.addCell("Nombre Completo");
        tablaPersonal.addCell(nombre);

        tablaPersonal.addCell("Fecha de Ingreso");
        tablaPersonal.addCell(fechaIngreso);

        tablaPersonal.addCell("Fecha de Retiro");
        tablaPersonal.addCell(fechaRetiro != null ? fechaRetiro : "No aplica");

        tablaPersonal.addCell("Teléfono");
        tablaPersonal.addCell(telefono);

        tablaPersonal.addCell("Cargo");
        tablaPersonal.addCell(cargo);

        tablaPersonal.addCell("Departamento");
        tablaPersonal.addCell(departamento);

        tablaPersonal.addCell("Tipo de Contrato");
        tablaPersonal.addCell(tipoContrato);

        document.add(new Paragraph("Datos Personales:", subTitulo));
        document.add(tablaPersonal);
        document.add(new Paragraph(" "));

        // Tabla info bancaria
        PdfPTable tablaBanco = new PdfPTable(2);
        tablaBanco.setWidthPercentage(100);
        tablaBanco.addCell(new PdfPCell(new Phrase("Campo", subTitulo)));
        tablaBanco.addCell(new PdfPCell(new Phrase("Información", subTitulo)));

        tablaBanco.addCell("Banco");
        tablaBanco.addCell(nombreBanco);

        tablaBanco.addCell("Tipo de Cuenta");
        tablaBanco.addCell(tipoCuenta);

        tablaBanco.addCell("Número de Cuenta");
        tablaBanco.addCell(numeroCuenta);

        document.add(new Paragraph("Información Bancaria:", subTitulo));
        document.add(tablaBanco);
        document.add(new Paragraph(" "));

        // Tabla devengados
        PdfPTable tablaDevengados = new PdfPTable(2);
        tablaDevengados.setWidthPercentage(100);
        tablaDevengados.addCell(new PdfPCell(new Phrase("Concepto", subTitulo)));
        tablaDevengados.addCell(new PdfPCell(new Phrase("Valor", subTitulo)));

        tablaDevengados.addCell("Salario");
        tablaDevengados.addCell(String.valueOf(salario));

        tablaDevengados.addCell("Subsidio de Transporte");
        tablaDevengados.addCell(String.valueOf(subTransporte));

        tablaDevengados.addCell("Gastos Representativos");
        tablaDevengados.addCell(String.valueOf(gastosRepresentativos));

        tablaDevengados.addCell("Viáticos");
        tablaDevengados.addCell(String.valueOf(viaticos));

        tablaDevengados.addCell("Comisiones");
        tablaDevengados.addCell(String.valueOf(comisiones));

        tablaDevengados.addCell("Horas Extra Diurnas");
        tablaDevengados.addCell(String.valueOf(horasExtraDiurnas));

        tablaDevengados.addCell("Horas Extra Nocturnas");
        tablaDevengados.addCell(String.valueOf(horasExtraNocturnas));

        tablaDevengados.addCell("Horas Extra Dominicales Diurnas");
        tablaDevengados.addCell(String.valueOf(horasExtraDomDiurnas));

        tablaDevengados.addCell("Horas Extra Dominicales Nocturnas");
        tablaDevengados.addCell(String.valueOf(horasExtraDomNocturnas));

        document.add(new Paragraph("Devengados:", subTitulo));
        document.add(tablaDevengados);
        document.add(new Paragraph(" "));

        // Tabla descuentos
        PdfPTable tablaDescuentos = new PdfPTable(2);
        tablaDescuentos.setWidthPercentage(100);
        tablaDescuentos.addCell(new PdfPCell(new Phrase("Concepto", subTitulo)));
        tablaDescuentos.addCell(new PdfPCell(new Phrase("Valor", subTitulo)));

        tablaDescuentos.addCell("Salud");
        tablaDescuentos.addCell(String.valueOf(salud));

        tablaDescuentos.addCell("Pensión");
        tablaDescuentos.addCell(String.valueOf(pension));

        tablaDescuentos.addCell("Crédito Empleado");
        tablaDescuentos.addCell(String.valueOf(creditoEmpleado));

        document.add(new Paragraph("Descuentos:", subTitulo));
        document.add(tablaDescuentos);
        document.add(new Paragraph(" "));

        // Tabla totales
        PdfPTable tablaTotales = new PdfPTable(2);
        tablaTotales.setWidthPercentage(100);
        tablaTotales.addCell(new PdfPCell(new Phrase("Concepto", subTitulo)));
        tablaTotales.addCell(new PdfPCell(new Phrase("Valor", subTitulo)));

        tablaTotales.addCell("Total Devengados");
        tablaTotales.addCell(String.valueOf(totalDevengados));

        tablaTotales.addCell("Total Descuentos");
        tablaTotales.addCell(String.valueOf(totalDescuentos));

        tablaTotales.addCell("Total a Pagar");
        tablaTotales.addCell(String.valueOf(totalPago));

        tablaTotales.addCell("Fecha de Pago");
        tablaTotales.addCell(fechaPago);

        document.add(new Paragraph("Totales de Pago:", subTitulo));
        document.add(tablaTotales);

        document.close();

        File archivo = new File(nombreArchivo);
        if(archivo.exists()) {
            java.awt.Desktop.getDesktop().open(archivo);
        }

        javax.swing.JOptionPane.showMessageDialog(this, "Reporte generado correctamente en: " + nombreArchivo);

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al generar el reporte: " + e.getMessage());
        e.printStackTrace();
    } finally {
        try {
            if(cn != null) cn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }


    }//GEN-LAST:event_jButton_ReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Reporte;
    private javax.swing.JComboBox<String> jComboBox_Empleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables


    private void CargarComboEmpleados(){
        Connection cn = Conexion.conectar();
        String sql = "SELECT Nombre_completo FROM empleado";
        
        Statement st;
        
        try{
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            jComboBox_Empleados.removeAllItems();
            jComboBox_Empleados.addItem("Seleccione Empleado:");
            while(rs.next()){
                jComboBox_Empleados.addItem(rs.getString("Nombre_completo"));
            }
            cn.close();
  
        }catch(SQLException e){
            System.out.println("Error al cargar Empleados"+e);
        }   
    }
    
    private void DatosEmpleado(){
        try{
            Connection cn = Conexion.conectar();
            String sql = "SELECT * FROM empleado WHERE Nombre_completo = '"+this.jComboBox_Empleados.getSelectedItem()+"'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                cedula = rs.getString("cedula");
            }
            
        }catch(SQLException e){
            System.out.println("Error al obtener datos del empleado: "+e);
        }
    }


}
