/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Conexion.Conexion;
import Controlador.Ctrl_Pagos;
import Controlador.GeneradorRecibo;
import Modelo.Pagos;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class InterRegistrarPago extends javax.swing.JInternalFrame {

    int id_pagos;
    String cedula;
    String total_descuentos;
    String total_devengados;
    
    public InterRegistrarPago() {
        initComponents();
        this.setSize(new Dimension(410, 340));
        this.setTitle("Liquidación Empleados");
        this.CargarComboEmpleados();
        this.CargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_Empleados = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtTotalDevengados = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTotalDescuentos = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtTotalPagar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Liquidacion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 350, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Total a Pagar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jComboBox_Empleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empleado:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 160, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 350, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre Empleado:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        txtTotalDevengados.setEditable(false);
        getContentPane().add(txtTotalDevengados, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Total Devengados:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        txtTotalDescuentos.setEditable(false);
        getContentPane().add(txtTotalDescuentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 160, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 350, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Total Descuentos:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txtTotalPagar.setEditable(false);
        getContentPane().add(txtTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 160, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Imprimir Recibo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Liquidar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String empleado = jComboBox_Empleados.getSelectedItem().toString();
        if(empleado.equalsIgnoreCase("Seleccione Empleado:") || txtTotalDescuentos.getText().isEmpty() || txtTotalDevengados.getText().isEmpty() || txtTotalPagar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Eliga el empleado que desea liquidar");
        }else{
            Ctrl_Pagos control = new Ctrl_Pagos();
            if(control.ExistePagoEmpleado(empleado)){
                JOptionPane.showMessageDialog(null, "Ya fue liquidado el empleado");
            }else{
                this.DatosEmpleado();
                
                this.TotalDevengados(cedula);
                this.TotalDescuentos(cedula);
                Pagos pagos = new Pagos();
                
                pagos.setId_pagos(id_pagos);
                pagos.setId_empleados(cedula);
                pagos.setTotal_devengados(total_devengados);
                pagos.setTotal_descuentos(txtTotalDescuentos.getText().trim());
                pagos.setTotal_pago(txtTotalPagar.getText().trim());
                
                LocalDate hoy = LocalDate.now();
                DateTimeFormatter formatoMySQL = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                String fechaFormateada = hoy.format(formatoMySQL);
                
                pagos.setFecha_pago(fechaFormateada);
                
                if(control.guardar(pagos)){
                    JOptionPane.showMessageDialog(null, "Liquidacion Exitosa");
                    this.Limpiar();
                }else{
                    JOptionPane.showMessageDialog(null, "Error al liquidar");
                }
                
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String empleado = jComboBox_Empleados.getSelectedItem().toString();
        this.DatosEmpleado();
        Ctrl_Pagos control = new Ctrl_Pagos();
        
        if(empleado.equalsIgnoreCase("Seleccione Empleado:") || txtTotalDescuentos.getText().isEmpty() || txtTotalDevengados.getText().isEmpty() || txtTotalPagar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Eliga el empleado que desea generar el reporte");
        }else{
            if(control.ExistePagoEmpleado(cedula)){
                GeneradorRecibo recibo = new GeneradorRecibo();
                recibo.generarReportePDF(cedula, empleado);
                JOptionPane.showMessageDialog(null, "Recibo generado");
                this.Limpiar();
            }else{
                JOptionPane.showMessageDialog(null, "El empleado aun no ha sido liquidado para generar reporte");
            }
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String empleado = jComboBox_Empleados.getSelectedItem().toString();
        this.DatosEmpleado();
      
        if(empleado.equalsIgnoreCase("Seleccione Empleado:") || txtTotalDescuentos.getText().isEmpty() || txtTotalDevengados.getText().isEmpty() || txtTotalPagar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Eliga el empleado que desea generar el reporte");
        }else{
            this.TotalDescuentos(cedula);
            this.TotalDevengados(cedula);
            Ctrl_Pagos control = new Ctrl_Pagos();
            Pagos pagos = new Pagos();
            
            pagos.setTotal_devengados(total_devengados);
            pagos.setTotal_descuentos(total_descuentos);
            pagos.setTotal_pago(txtTotalPagar.getText().trim());
            
            LocalDate hoy = LocalDate.now();
                DateTimeFormatter formatoMySQL = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                String fechaFormateada = hoy.format(formatoMySQL);
                
            pagos.setFecha_pago(fechaFormateada);
            
            if(control.actualizar(pagos, cedula)){
                JOptionPane.showMessageDialog(null, "Actualizacion de liquidacion exitosa!");
            }else{
                JOptionPane.showMessageDialog(null, "Error al actualizar");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox_Empleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtTotalDescuentos;
    private javax.swing.JTextField txtTotalDevengados;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables

    private void CargarComboEmpleados(){
            Connection cn = Conexion.conectar();
            String sql = "SELECT Nombre_completo FROM empleado";

            Statement st;

            try{
                st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);

                jComboBox_Empleados.removeAllItems();
                jComboBox_Empleados.addItem("Seleccione Empleado:");
                while(rs.next()){
                    jComboBox_Empleados.addItem(rs.getString("Nombre_completo"));
                }
                cn.close();

            }catch(SQLException e){
                System.out.println("Error al cargar Empleados"+e);
            }
    }
    
    private void DatosEmpleado(){
        try{
            Connection cn = Conexion.conectar();
            String sql = "SELECT cedula FROM empleado WHERE Nombre_completo = '"+this.jComboBox_Empleados.getSelectedItem()+"'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                cedula = rs.getString("cedula");
            }
            
        }catch(SQLException e){
            System.out.println("Error al obtener datos del empleado: "+e);
        }
    }
    
     private void TotalDevengados(String cedula){
        try{
            Connection cn = Conexion.conectar();
            String sql = "SELECT SUM(salario+Sub_transporte+Gastos_representativos+Viaticos+Comisiones+ Horas_extra_diurnas+Horas_extra_nocturnas+ Horas_extra_dominicales_diurnas+Horas_extra_dominicales_nocturnas) as Total_Devengados FROM devengados WHERE id_empleado = '"+cedula+"'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                total_devengados = rs.getString("Total_Devengados");
            }
        }catch(SQLException e){
            System.out.println("Error al obtener total de devengado");
        }
    }
    

    private void TotalDescuentos(String cedula){
        try{
            Connection cn = Conexion.conectar();
            String sql = "SELECT SUM(salud+pension+credito_empleado) as Total_Descuentos FROM Descuentos WHERE id_empleado = '"+cedula+"'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                total_descuentos = rs.getString("Total_Descuentos");
            }
        }catch(SQLException e){
            System.out.println("Error al obtener total de descuento");
        }
    }
    
    private void CargarDatos(){
        jComboBox_Empleados.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // 1. Obtener cédula del empleado seleccionado
            DatosEmpleado();  // Este método debe actualizar la variable "cedula"

            if (cedula != null && !cedula.isEmpty()) {
                // 2. Calcular totales
                TotalDevengados(cedula);
                TotalDescuentos(cedula);
                
                Double tot_devengados;
                Double tor_descuentos;
                
                

                // 3. Mostrar resultados, asegurando que nunca queden en blanco o null
                if (total_devengados != null && !total_devengados.isEmpty()) {
                    txtTotalDevengados.setText(total_devengados);
                    tot_devengados = Double.valueOf(total_devengados);
                } else {
                    txtTotalDevengados.setText("0");
                    tot_devengados = 0.0;
                }

                if (total_descuentos != null && !total_descuentos.isEmpty()) {
                    txtTotalDescuentos.setText(total_descuentos);
                    tor_descuentos = Double.valueOf(total_descuentos);
                } else {
                    txtTotalDescuentos.setText("0");
                    tor_descuentos = 0.0;
                }
                
                Double total = tot_devengados - tor_descuentos;
                txtTotalPagar.setText(String.valueOf(total));
                
            } else {
                // Si no hay cédula, reiniciar a cero
                txtTotalDevengados.setText("0");
                txtTotalDescuentos.setText("0");
            }
        }
    });

    }
    
    public void Limpiar(){
        jComboBox_Empleados.setSelectedItem("Seleccione Empleado:");
        txtTotalDescuentos.setText("");
        txtTotalDevengados.setText("");
        txtTotalPagar.setText("");
    }

}
