/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Conexion.Conexion;
import Controlador.Ctrl_Descuentos;
import Controlador.Ctrl_Devengados;
import Modelo.Descuentos;
import Modelo.Devengados;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author LENOVO
 */
public class InterDevengadosEmpleados extends javax.swing.JInternalFrame {

    private int id_devengados;
    private String id_cedula;
    private String tipo_contrato;
    

    
    
    public InterDevengadosEmpleados() {
        initComponents();
        this.setSize(new Dimension(1050, 500));
        this.setTitle("Informacion Devengados de los empleados.");
        this.CargarComboEmpleados();
        this.DatosDevengados();
        this.CargarDatosDevengados();
        // ActionListener para que reaccione al cambio de selección
        jComboBox_Empleados.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (jComboBox_Empleados.getSelectedIndex() > 0) { // evita ejecutar si está en "Seleccione Empleado"
                TipoContratoEmpleado();
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox_Empleados = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtHorasTrabajadas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSubTransporte = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGastos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtViaticos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtComisiones = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtHorasDiurnas = new javax.swing.JTextField();
        txtHorasNocturnas = new javax.swing.JTextField();
        txtHorasDiurnasFestivas = new javax.swing.JTextField();
        txtHorasNocturnasFestivas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtValorHorasDiurnas = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtValorHorasNocturnas = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtValorHoraDiurnaFestiva = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtValorNocturnaFestiva = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jBoton_Calcular = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Horas Trabajadas:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, -1));

        jComboBox_Empleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Empleado:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 1000, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Elegir Empleado:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 130, -1));

        txtHorasTrabajadas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHorasTrabajadasKeyTyped(evt);
            }
        });
        getContentPane().add(txtHorasTrabajadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Salario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 150, -1));

        txtSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 160, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Sub de Transporte:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 170, -1));

        txtSubTransporte.setEditable(false);
        txtSubTransporte.setText("200000");
        getContentPane().add(txtSubTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 160, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Gastos Representativos:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 180, -1));

        txtGastos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGastosKeyTyped(evt);
            }
        });
        getContentPane().add(txtGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 160, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Viaticos:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 180, -1));

        txtViaticos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtViaticosKeyTyped(evt);
            }
        });
        getContentPane().add(txtViaticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 160, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Comisiones:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, -1));

        txtComisiones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtComisionesKeyTyped(evt);
            }
        });
        getContentPane().add(txtComisiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 160, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Modulo Horas Extra:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 540, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Administrar Devengados del Empleado");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Cantidad Horas Extra Diurnas:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 200, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Cantidad Horas Extra Nocturnas:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 200, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Cantidad Horas Extra Diurnas Domincales / Festivas:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 300, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Cantidad Horas Extra Nocturnas Domincales / Festivas:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 300, 20));

        txtHorasDiurnas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHorasDiurnasKeyTyped(evt);
            }
        });
        getContentPane().add(txtHorasDiurnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 60, -1));

        txtHorasNocturnas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHorasNocturnasKeyTyped(evt);
            }
        });
        getContentPane().add(txtHorasNocturnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 60, -1));

        txtHorasDiurnasFestivas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHorasDiurnasFestivasKeyTyped(evt);
            }
        });
        getContentPane().add(txtHorasDiurnasFestivas, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 60, -1));

        txtHorasNocturnasFestivas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHorasNocturnasFestivasKeyTyped(evt);
            }
        });
        getContentPane().add(txtHorasNocturnasFestivas, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 60, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Valor:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, -1, -1));

        txtValorHorasDiurnas.setEditable(false);
        getContentPane().add(txtValorHorasDiurnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 150, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Valor:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, -1, -1));

        txtValorHorasNocturnas.setEditable(false);
        getContentPane().add(txtValorHorasNocturnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 150, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Valor:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, -1, -1));

        txtValorHoraDiurnaFestiva.setEditable(false);
        getContentPane().add(txtValorHoraDiurnaFestiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, 150, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Valor:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, -1, -1));

        txtValorNocturnaFestiva.setEditable(false);
        getContentPane().add(txtValorNocturnaFestiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, 150, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Total:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, -1, -1));

        txtTotal.setEditable(false);
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, 150, -1));

        jBoton_Calcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBoton_Calcular.setText("Calcular Horas Extra");
        jBoton_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton_CalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jBoton_Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Guardar ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 400, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHorasDiurnasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHorasDiurnasKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si el carácter es un número, un punto o la tecla de retroceso
        boolean esNumero = (caracter >= '0' && caracter <= '9');
        boolean esPunto = (caracter == '.');
        boolean esBackspace = (caracter == KeyEvent.VK_BACK_SPACE);

        // Verificar si ya hay un punto en el texto
        boolean yaTienePunto = txtHorasDiurnas.getText().contains(".");

        // Si el carácter no es un número, no es un punto válido, no es backspace, o se supera la longitud máxima
        if (!esNumero && !(esPunto && !yaTienePunto) && !esBackspace) {
            evt.consume(); // Ignorar el carácter
        }
    }//GEN-LAST:event_txtHorasDiurnasKeyTyped

    private void txtHorasNocturnasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHorasNocturnasKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si el carácter es un número, un punto o la tecla de retroceso
        boolean esNumero = (caracter >= '0' && caracter <= '9');
        boolean esPunto = (caracter == '.');
        boolean esBackspace = (caracter == KeyEvent.VK_BACK_SPACE);

        // Verificar si ya hay un punto en el texto
        boolean yaTienePunto = txtHorasNocturnas.getText().contains(".");

        // Si el carácter no es un número, no es un punto válido, no es backspace, o se supera la longitud máxima
        if (!esNumero && !(esPunto && !yaTienePunto) && !esBackspace) {
            evt.consume(); // Ignorar el carácter
        }
    }//GEN-LAST:event_txtHorasNocturnasKeyTyped

    private void txtHorasDiurnasFestivasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHorasDiurnasFestivasKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si el carácter es un número, un punto o la tecla de retroceso
        boolean esNumero = (caracter >= '0' && caracter <= '9');
        boolean esPunto = (caracter == '.');
        boolean esBackspace = (caracter == KeyEvent.VK_BACK_SPACE);

        // Verificar si ya hay un punto en el texto
        boolean yaTienePunto = txtHorasDiurnasFestivas.getText().contains(".");

        // Si el carácter no es un número, no es un punto válido, no es backspace, o se supera la longitud máxima
        if (!esNumero && !(esPunto && !yaTienePunto) && !esBackspace) {
            evt.consume(); // Ignorar el carácter
        }
    }//GEN-LAST:event_txtHorasDiurnasFestivasKeyTyped

    private void txtHorasNocturnasFestivasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHorasNocturnasFestivasKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si el carácter es un número, un punto o la tecla de retroceso
        boolean esNumero = (caracter >= '0' && caracter <= '9');
        boolean esPunto = (caracter == '.');
        boolean esBackspace = (caracter == KeyEvent.VK_BACK_SPACE);

        // Verificar si ya hay un punto en el texto
        boolean yaTienePunto = txtHorasNocturnasFestivas.getText().contains(".");

        // Si el carácter no es un número, no es un punto válido, no es backspace, o se supera la longitud máxima
        if (!esNumero && !(esPunto && !yaTienePunto) && !esBackspace) {
            evt.consume(); // Ignorar el carácter
        }
    }//GEN-LAST:event_txtHorasNocturnasFestivasKeyTyped

    private void txtSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalarioKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si el carácter es un número, un punto o la tecla de retroceso
        boolean esNumero = (caracter >= '0' && caracter <= '9');
        boolean esPunto = (caracter == '.');
        boolean esBackspace = (caracter == KeyEvent.VK_BACK_SPACE);

        // Verificar si ya hay un punto en el texto
            boolean yaTienePunto = txtSalario.getText().contains(".");

        // Si el carácter no es un número, no es un punto válido, no es backspace, o se supera la longitud máxima
        if (!esNumero && !(esPunto && !yaTienePunto) && !esBackspace) {
            evt.consume(); // Ignorar el carácter
        }
    }//GEN-LAST:event_txtSalarioKeyTyped

    private void txtGastosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGastosKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si el carácter es un número, un punto o la tecla de retroceso
        boolean esNumero = (caracter >= '0' && caracter <= '9');
        boolean esPunto = (caracter == '.');
        boolean esBackspace = (caracter == KeyEvent.VK_BACK_SPACE);

        // Verificar si ya hay un punto en el texto
        boolean yaTienePunto = txtGastos.getText().contains(".");

        // Si el carácter no es un número, no es un punto válido, no es backspace, o se supera la longitud máxima
        if (!esNumero && !(esPunto && !yaTienePunto) && !esBackspace) {
            evt.consume(); // Ignorar el carácter
        }
    }//GEN-LAST:event_txtGastosKeyTyped

    private void txtViaticosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtViaticosKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si el carácter es un número, un punto o la tecla de retroceso
        boolean esNumero = (caracter >= '0' && caracter <= '9');
        boolean esPunto = (caracter == '.');
        boolean esBackspace = (caracter == KeyEvent.VK_BACK_SPACE);

        // Verificar si ya hay un punto en el texto
        boolean yaTienePunto = txtViaticos.getText().contains(".");

        // Si el carácter no es un número, no es un punto válido, no es backspace, o se supera la longitud máxima
        if (!esNumero && !(esPunto && !yaTienePunto) && !esBackspace) {
            evt.consume(); // Ignorar el carácter
        }
    }//GEN-LAST:event_txtViaticosKeyTyped

    private void txtComisionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComisionesKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si el carácter es un número, un punto o la tecla de retroceso
        boolean esNumero = (caracter >= '0' && caracter <= '9');
        boolean esPunto = (caracter == '.');
        boolean esBackspace = (caracter == KeyEvent.VK_BACK_SPACE);

        // Verificar si ya hay un punto en el texto
        boolean yaTienePunto = txtComisiones.getText().contains(".");

        // Si el carácter no es un número, no es un punto válido, no es backspace, o se supera la longitud máxima
        if (!esNumero && !(esPunto && !yaTienePunto) && !esBackspace) {
            evt.consume(); // Ignorar el carácter
        }
    }//GEN-LAST:event_txtComisionesKeyTyped

    private void txtHorasTrabajadasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHorasTrabajadasKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si el carácter es un número, un punto o la tecla de retroceso
        boolean esNumero = (caracter >= '0' && caracter <= '9');
        boolean esPunto = (caracter == '.');
        boolean esBackspace = (caracter == KeyEvent.VK_BACK_SPACE);

        // Verificar si ya hay un punto en el texto
        boolean yaTienePunto = txtHorasTrabajadas.getText().contains(".");

        // Si el carácter no es un número, no es un punto válido, no es backspace, o se supera la longitud máxima
        if (!esNumero && !(esPunto && !yaTienePunto) && !esBackspace) {
            evt.consume(); // Ignorar el carácter
        }
    }//GEN-LAST:event_txtHorasTrabajadasKeyTyped

    private void jBoton_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton_CalcularActionPerformed
       if(txtSalario.getText().isEmpty()  ||txtHorasDiurnas.getText().isEmpty() || txtHorasNocturnas.getText().isEmpty() || txtHorasDiurnasFestivas.getText().isEmpty() || txtHorasNocturnasFestivas.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Complete los campos necesarios para calcular el valor de las horas extras!");
       }else{
           double salario = Double.parseDouble(txtSalario.getText().trim());
           double horas_diurnas = Double.parseDouble(txtHorasDiurnas.getText().trim());
           double horas_nocturnas = Double.parseDouble(txtHorasNocturnas.getText().trim());
           double horas_diurnas_festivas = Double.parseDouble(txtHorasDiurnasFestivas.getText().trim());
           double horas_nocturnas_festivas = Double.parseDouble(txtHorasNocturnasFestivas.getText().trim());
           
           double salario_hora = salario/240;
           
           double valor_horas_diurnas = (horas_diurnas)*(salario_hora)*(1.25);
           double valor_horas_nocturnas = (horas_nocturnas)*(salario_hora)*(1.75);
           double valor_horas_diurnas_festivas = (horas_diurnas_festivas)*(salario_hora)*(2);
           double valor_horas_nocturnas_festivas = (horas_nocturnas_festivas)*(salario_hora)*(2.5);
           
           double total = valor_horas_diurnas + valor_horas_nocturnas + valor_horas_diurnas_festivas + valor_horas_nocturnas_festivas;
           
           txtValorHorasDiurnas.setText(String.valueOf(valor_horas_diurnas));
           txtValorHorasNocturnas.setText(String.valueOf(valor_horas_nocturnas));
           txtValorHoraDiurnaFestiva.setText(String.valueOf(valor_horas_diurnas_festivas));
           txtValorNocturnaFestiva.setText(String.valueOf(valor_horas_nocturnas_festivas));
           
           txtTotal.setText(String.valueOf(total));
           
       }
    }//GEN-LAST:event_jBoton_CalcularActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String empleado = jComboBox_Empleados.getSelectedItem().toString();

    if (empleado.equalsIgnoreCase("Seleccione un Empleado:") || txtSalario.getText().trim().isEmpty() || txtHorasTrabajadas.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Elija el empleado y/o su salario y/o sus horas trabajadas");
    } else {
        Ctrl_Devengados controldevengados = new Ctrl_Devengados();

        if (controldevengados.ExisteDevengadoEmpleado(empleado)) {
            JOptionPane.showMessageDialog(null, "El empleado ya existe en Devengados!");
        } else {
            // Obtener datos relacionados con el empleado y contrato
            this.DatosEmpleado();
            this.TipoContratoEmpleado();

            // Crear objeto Devengados y asignar valores
            Devengados dev = new Devengados();
            dev.setId_devengados(id_devengados);
            dev.setId_empleado(id_cedula);
            dev.setSalario(txtSalario.getText().trim());
            dev.setSub_transporte(txtSubTransporte.getText().trim());
            dev.setGastos(obtenerValorCampo(txtGastos));
            dev.setViaticos(obtenerValorCampo(txtViaticos));
            dev.setComisiones(obtenerValorCampo(txtComisiones));
            dev.setHoras_trabajadas(obtenerValorCampo(txtHorasTrabajadas));
            dev.setCantidad_horas_diurnas(obtenerValorCampo(txtHorasDiurnas));
            dev.setCantidad_horas_nocturnas(obtenerValorCampo(txtHorasNocturnas));
            dev.setCantidad_horas_diurnas_festivas(obtenerValorCampo(txtHorasDiurnasFestivas));
            dev.setCantidad_horas_nocturnas_festivas(obtenerValorCampo(txtHorasNocturnasFestivas));
            dev.setHoras_extra_diurnas(obtenerValorCampo(txtValorHorasDiurnas));
            dev.setHoras_extra_nocturnas(obtenerValorCampo(txtValorHorasNocturnas));
            dev.setHoras_extra_dominicales_diurnas(obtenerValorCampo(txtValorHoraDiurnaFestiva));
            dev.setHoras_extra_dominicales_nocturnas(obtenerValorCampo(txtValorNocturnaFestiva));

            // Guardar en base de datos
            Ctrl_Devengados control = new Ctrl_Devengados();

            if (control.guardar(dev)) {
                JOptionPane.showMessageDialog(null, "Devengados guardados con éxito.");

                // Validar tipo de contrato y calcular descuentos
                if (tipo_contrato.equalsIgnoreCase("Término indefinido")
                    || tipo_contrato.equalsIgnoreCase("Término fijo")
                    || tipo_contrato.equalsIgnoreCase("Obra o labor")
                    || tipo_contrato.equalsIgnoreCase("Ocasional o accidental")) {

                    String salarioTexto = txtSalario.getText().trim();
                    double salario;
                    try {
                        salario = Double.parseDouble(salarioTexto);
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "El salario ingresado no es un número válido.");
                        return;
                    }

                    double pension = salario * 0.04;
                    double salud = salario * 0.04;
                    double credito = 0;

                    Descuentos descuento = new Descuentos();
                    Ctrl_Descuentos controlDes = new Ctrl_Descuentos();

                    descuento.setId_empleado(id_cedula);
                    descuento.setSalud(String.valueOf(salud));
                    descuento.setPension(String.valueOf(pension));
                    descuento.setCredito(String.valueOf(credito));

                    if (controlDes.guardar(descuento)) {
                        JOptionPane.showMessageDialog(null, "Descuentos guardados con éxito.");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al guardar descuento.");
                    }
                }

                this.Limpiar();

            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar devengados.");
            }
        }
}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String empleado = jComboBox_Empleados.getSelectedItem().toString();
        
        if(empleado.equalsIgnoreCase("Seleccione un Empleado:") || txtSalario.getText().isEmpty() || txtHorasTrabajadas.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Elija el empleado y/o su salario y/o sus horas trabajadas");
        } else{
                    this.DatosDevengados();
                    Devengados dev = new Devengados();
                    
                    dev.setSalario(txtSalario.getText().trim());
                    dev.setSub_transporte(txtSubTransporte.getText().trim());
                    dev.setGastos(obtenerValorCampo(txtGastos));
                    dev.setViaticos(obtenerValorCampo(txtViaticos));
                    dev.setComisiones(obtenerValorCampo(txtComisiones));
                    dev.setHoras_trabajadas(obtenerValorCampo(txtHorasTrabajadas)); 
                    dev.setCantidad_horas_diurnas(obtenerValorCampo(txtHorasDiurnas));
                    dev.setCantidad_horas_nocturnas(obtenerValorCampo(txtHorasNocturnas));
                    dev.setCantidad_horas_diurnas_festivas(obtenerValorCampo(txtHorasDiurnasFestivas));
                    dev.setCantidad_horas_nocturnas_festivas(obtenerValorCampo(txtHorasNocturnasFestivas));
                    dev.setHoras_extra_diurnas(obtenerValorCampo(txtValorHorasDiurnas));
                    dev.setHoras_extra_nocturnas(obtenerValorCampo(txtValorHorasNocturnas));
                    dev.setHoras_extra_dominicales_diurnas(obtenerValorCampo(txtValorHoraDiurnaFestiva));
                    dev.setHoras_extra_dominicales_nocturnas(obtenerValorCampo(txtValorNocturnaFestiva));
                    // Guardar en base de datos
                    Ctrl_Devengados control = new Ctrl_Devengados();
                    
                    if(control.actualizar(dev, id_devengados)){
                        JOptionPane.showMessageDialog(null, "Información actualzida con éxito!");
                        this.Limpiar();
                    }else{
                        JOptionPane.showMessageDialog(null, "Error al actualizar");
                    }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBoton_Calcular;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox_Empleados;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtComisiones;
    private javax.swing.JTextField txtGastos;
    private javax.swing.JTextField txtHorasDiurnas;
    private javax.swing.JTextField txtHorasDiurnasFestivas;
    private javax.swing.JTextField txtHorasNocturnas;
    private javax.swing.JTextField txtHorasNocturnasFestivas;
    private javax.swing.JTextField txtHorasTrabajadas;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtSubTransporte;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtValorHoraDiurnaFestiva;
    private javax.swing.JTextField txtValorHorasDiurnas;
    private javax.swing.JTextField txtValorHorasNocturnas;
    private javax.swing.JTextField txtValorNocturnaFestiva;
    private javax.swing.JTextField txtViaticos;
    // End of variables declaration//GEN-END:variables
    
    private void CargarComboEmpleados(){
        Connection cn = Conexion.conectar();
        String sql = "SELECT Nombre_completo FROM empleado";
        
        Statement st;
        
        try{
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            jComboBox_Empleados.removeAllItems();
            jComboBox_Empleados.addItem("Seleccione Empleado:");
            while(rs.next()){
                jComboBox_Empleados.addItem(rs.getString("Nombre_completo"));
            }
            cn.close();
  
        }catch(SQLException e){
            System.out.println("Error al cargar Empleados"+e);
        }
    }
    
    private String obtenerValorCampo(JTextField campo) {
    return campo.getText().trim().isEmpty() ? "0" : campo.getText().trim();
    }
    
    private void DatosEmpleado(){
        try{
            Connection cn = Conexion.conectar();
            String sql = "SELECT * FROM empleado WHERE Nombre_completo = '"+this.jComboBox_Empleados.getSelectedItem()+"'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                id_cedula = rs.getString("cedula");
            }
            
        }catch(SQLException e){
            System.out.println("Error al obtener datos del empleado: "+e);
        }
    }
    
    private void DatosDevengados(){
        try{
            Connection cn = Conexion.conectar();
            String sql = "SELECT * FROM Devengados d INNER JOIN empleado e ON d.id_empleado = e.cedula WHERE e.Nombre_completo = '"+this.jComboBox_Empleados.getSelectedItem()+"'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                id_devengados = rs.getInt("d.id_devengados");
            }
            
        }catch(SQLException e){
            System.out.println("Error al obtener datos del empleado: "+e);
        }
    }
    
    private void TipoContratoEmpleado(){
        try{
            Connection cn = Conexion.conectar();
            String sql = "SELECT c.tipo_contrato FROM empleado e inner join tipoContrato c on e.id_tipoContrato = c.id_tipoContrato where e.Nombre_completo = '"+this.jComboBox_Empleados.getSelectedItem()+"'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                tipo_contrato = rs.getString("c.tipo_contrato");
                this.ajustarCamposPorTipoContrato(tipo_contrato);
            }
            
        }catch(SQLException e){
            System.out.println("Error al obtener datos del empleado: "+e);
        }
    }

            private void ajustarCamposPorTipoContrato(String tipoContrato) {
                boolean tieneHorasExtra = false;
                boolean tieneViaticos = false;
                boolean tieneComisiones = false;
                boolean tieneGastos = false;
                boolean tieneSalario = true;
                boolean tieneHorasTrabajadas = true;

                switch (tipoContrato) {
                    case "Término indefinido":
                    case "Término fijo":
                    case "Obra o labor":
                    case "Ocasional o accidental":
                        tieneHorasExtra = true;
                        tieneViaticos = true;
                        tieneComisiones = true;
                        tieneGastos = true;
                        break;

                    case "Aprendizaje":
                        tieneHorasExtra = false;
                        tieneViaticos = true;
                        tieneComisiones = false;
                        tieneGastos = false;
                        break;

                    case "Prestación de servicios":
                        tieneHorasExtra = false;
                        tieneViaticos = true;
                        tieneComisiones = true; // Si lo pactan
                        tieneGastos = true;
                        tieneSalario = false; // Pagan por honorarios, no salario
                        break;
                }

                // Horas extra (pueden ingresar cantidad, pero los valores son calculados y no editables)
                txtHorasDiurnas.setEnabled(tieneHorasExtra);
                txtHorasNocturnas.setEnabled(tieneHorasExtra);
                txtHorasDiurnasFestivas.setEnabled(tieneHorasExtra);
                txtHorasNocturnasFestivas.setEnabled(tieneHorasExtra);

                // Los valores de horas extra son solo de visualización
                txtValorHorasDiurnas.setEditable(false);
                txtValorHorasNocturnas.setEditable(false);
                txtValorHoraDiurnaFestiva.setEditable(false);
                txtValorNocturnaFestiva.setEditable(false);

            }

            public void Limpiar(){
                jComboBox_Empleados.setSelectedItem("Seleccione un Empleado:");
                txtSalario.setText("");
                txtHorasTrabajadas.setText("");
                txtGastos.setText("");
                txtViaticos.setText("");
                txtComisiones.setText("");
                txtHorasDiurnas.setText("");
                txtHorasNocturnas.setText("");
                txtHorasDiurnasFestivas.setText("");
                txtHorasNocturnasFestivas.setText("");
                txtValorHorasDiurnas.setText("");
                txtValorHorasNocturnas.setText("");
                txtValorHoraDiurnaFestiva.setText("");
                txtValorNocturnaFestiva.setText("");
                txtTotal.setText("");

            }
        private void CargarDatosDevengados() {
        jComboBox_Empleados.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String nombreEmpleado = jComboBox_Empleados.getSelectedItem().toString();

            if (nombreEmpleado.equalsIgnoreCase("Seleccione un Empleado:")) {
                return;
            }

            try {
                Connection cn = Conexion.conectar();
                String sql = "SELECT d.* FROM devengados d " +
                             "INNER JOIN empleado e ON d.id_empleado = e.cedula " +
                             "WHERE e.Nombre_completo = ?";
                PreparedStatement pst = cn.prepareStatement(sql);
                pst.setString(1, nombreEmpleado);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    // Carga los datos a los campos
                    txtSalario.setText(rs.getString("salario"));
                    txtSubTransporte.setText(rs.getString("sub_transporte"));
                    txtGastos.setText(rs.getString("gastos_representativos"));
                    txtViaticos.setText(rs.getString("viaticos"));
                    txtComisiones.setText(rs.getString("comisiones"));
                    txtHorasTrabajadas.setText(rs.getString("horas_trabajadas"));

                    txtHorasDiurnas.setText(rs.getString("cantidad_horas_diurnas"));
                    txtHorasNocturnas.setText(rs.getString("cantidad_horas_nocturnas"));
                    txtHorasDiurnasFestivas.setText(rs.getString("cantidad_horas_diurnas_festivas"));
                    txtHorasNocturnasFestivas.setText(rs.getString("cantidad_horas_nocturnas_festivas"));

                    txtValorHorasDiurnas.setText(rs.getString("horas_extra_diurnas"));
                    txtValorHorasNocturnas.setText(rs.getString("horas_extra_nocturnas"));
                    txtValorHoraDiurnaFestiva.setText(rs.getString("horas_extra_dominicales_diurnas"));
                    txtValorNocturnaFestiva.setText(rs.getString("horas_extra_dominicales_nocturnas"));

                    id_devengados = rs.getInt("id_devengados");

                } else {
                    txtSalario.setText("");
                    txtHorasTrabajadas.setText("");
                    txtGastos.setText("");
                    txtViaticos.setText("");
                    txtComisiones.setText("");
                    txtHorasDiurnas.setText("");
                    txtHorasNocturnas.setText("");
                    txtHorasDiurnasFestivas.setText("");
                    txtHorasNocturnasFestivas.setText("");
                    txtValorHorasDiurnas.setText("");
                    txtValorHorasNocturnas.setText("");
                    txtValorHoraDiurnaFestiva.setText("");
                    txtValorNocturnaFestiva.setText("");
                    txtTotal.setText("");
                }

                cn.close();
            } catch (SQLException ex) {
                System.out.println("Error al cargar datos de devengados: " + ex);
            }
        }
        });
    }
    
}





