/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Conexion.Conexion;
import Controlador.Ctrl_Descuentos;
import Modelo.Descuentos;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class InterDescuentosEmpleados extends javax.swing.JInternalFrame {
    
    
    String credito;
    String cedula;
    String salud;
    String pension;
    String Contrato;
    
    Double salario;
    
    
    public InterDescuentosEmpleados() {
        initComponents();
        this.setSize(new Dimension(640, 417));
        this.setTitle("Informacion Descuentos de los empleados.");
        this.CargarComboEmpleados();
        this.CargarDatosDescuentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox_Empleados = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCredito = new javax.swing.JTextField();
        txtSalud = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPension = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Administrar Descuento del Empleado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Eliga Empleado:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 110, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 480, -1));

        jComboBox_Empleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empleado:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Pension:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 480, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cuota Credito:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 480, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("El total de los descuentos no pueden ser mayores al 40% del salario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Salud:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        txtCredito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCreditoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 170, -1));

        txtSalud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaludKeyTyped(evt);
            }
        });
        getContentPane().add(txtSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 170, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Si el empleado tiene un credito. Dijite el valor de la cuota.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        txtPension.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPensionKeyTyped(evt);
            }
        });
        getContentPane().add(txtPension, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.Contrato();
        if(Contrato.equalsIgnoreCase("Aprendizaje") || Contrato.equalsIgnoreCase("Prestación de servicios")){
            JOptionPane.showMessageDialog(null, "El empleado no puede tener descuentos por su tipo de contrato laboral");
        }else{
            this.DatosEmpleado();
            this.Salario(cedula);
            
            salud = txtSalud.getText().trim();
            pension = txtPension.getText().trim();
            credito = txtCredito.getText().trim();
            
            Double Salud = Double.valueOf(salud);
            Double Pension = Double.valueOf(pension);
            Double Credito = Double.valueOf(credito);
            
            Double Minimo = salario * 0.4;
            Double Total = Salud + Pension + Credito;
            
            if(Total > Minimo){
                JOptionPane.showMessageDialog(null, "Error. Los descuentos superan el 40% del salario del empleado");
            }else{  
                Descuentos descuentos = new Descuentos();
                Ctrl_Descuentos control = new Ctrl_Descuentos();

                descuentos.setSalud(salud);
                descuentos.setPension(pension);
                descuentos.setCredito(credito);

                if(control.actualizar(descuentos, cedula)){
                    JOptionPane.showMessageDialog(null, "Información actualzida con éxito!");
                }else{
                    JOptionPane.showMessageDialog(null, "Error al actualizar");
                }
                this.Limpiar();
            
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSaludKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaludKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si el carácter es un número, un punto o la tecla de retroceso
        boolean esNumero = (caracter >= '0' && caracter <= '9');
        boolean esPunto = (caracter == '.');
        boolean esBackspace = (caracter == KeyEvent.VK_BACK_SPACE);

        // Verificar si ya hay un punto en el texto
        boolean yaTienePunto = txtSalud.getText().contains(".");

        // Si el carácter no es un número, no es un punto válido, no es backspace, o se supera la longitud máxima
        if (!esNumero && !(esPunto && !yaTienePunto) && !esBackspace) {
            evt.consume(); // Ignorar el carácter
        }
    }//GEN-LAST:event_txtSaludKeyTyped

    private void txtCreditoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCreditoKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si el carácter es un número, un punto o la tecla de retroceso
        boolean esNumero = (caracter >= '0' && caracter <= '9');
        boolean esPunto = (caracter == '.');
        boolean esBackspace = (caracter == KeyEvent.VK_BACK_SPACE);

        // Verificar si ya hay un punto en el texto
        boolean yaTienePunto = txtCredito.getText().contains(".");

        // Si el carácter no es un número, no es un punto válido, no es backspace, o se supera la longitud máxima
        if (!esNumero && !(esPunto && !yaTienePunto) && !esBackspace) {
            evt.consume(); // Ignorar el carácter
        }
    }//GEN-LAST:event_txtCreditoKeyTyped

    private void txtPensionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPensionKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si el carácter es un número, un punto o la tecla de retroceso
        boolean esNumero = (caracter >= '0' && caracter <= '9');
        boolean esPunto = (caracter == '.');
        boolean esBackspace = (caracter == KeyEvent.VK_BACK_SPACE);

        // Verificar si ya hay un punto en el texto
        boolean yaTienePunto = txtCredito.getText().contains(".");

        // Si el carácter no es un número, no es un punto válido, no es backspace, o se supera la longitud máxima
        if (!esNumero && !(esPunto && !yaTienePunto) && !esBackspace) {
            evt.consume(); // Ignorar el carácter
        }
    }//GEN-LAST:event_txtPensionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox_Empleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtCredito;
    private javax.swing.JTextField txtPension;
    private javax.swing.JTextField txtSalud;
    // End of variables declaration//GEN-END:variables

    private void CargarComboEmpleados(){
        Connection cn = Conexion.conectar();
        String sql = "SELECT Nombre_completo FROM empleado";
        
        Statement st;
        
        try{
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            jComboBox_Empleados.removeAllItems();
            jComboBox_Empleados.addItem("Seleccione Empleado:");
            while(rs.next()){
                jComboBox_Empleados.addItem(rs.getString("Nombre_completo"));
            }
            cn.close();
  
        }catch(SQLException e){
            System.out.println("Error al cargar Empleados"+e);
        }
    }
    

    private void DatosEmpleado(){
        try{
            Connection cn = Conexion.conectar();
            String sql = "SELECT cedula FROM empleado WHERE Nombre_completo = '"+this.jComboBox_Empleados.getSelectedItem()+"'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                cedula = rs.getString("cedula");
            }
            
        }catch(SQLException e){
            System.out.println("Error al obtener datos del empleado: "+e);
        }
    }

    
    private void CargarDatosDescuentos() {
    jComboBox_Empleados.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String nombreEmpleado = jComboBox_Empleados.getSelectedItem().toString();

            if (nombreEmpleado.equalsIgnoreCase("Seleccione un Empleado:")) {
                txtSalud.setText("");
                txtPension.setText("");
                return;
            }

            try {
                Connection cn = Conexion.conectar();

                String sqlDescuentos = "SELECT salud, pension FROM descuentos d " +
                                       "INNER JOIN empleado e ON d.id_empleado = e.cedula " +
                                       "WHERE e.Nombre_completo = ?";
                PreparedStatement pstDesc = cn.prepareStatement(sqlDescuentos);
                pstDesc.setString(1, nombreEmpleado);
                ResultSet rsDesc = pstDesc.executeQuery();

                if (rsDesc.next()) {
                    txtSalud.setText(rsDesc.getString("salud"));
                    txtPension.setText(rsDesc.getString("pension"));
                } else {
                    txtSalud.setText("");
                    txtPension.setText("");
                }

                cn.close();
            } catch (SQLException ex) {
                System.out.println("Error al cargar datos de descuentos: " + ex);
                JOptionPane.showMessageDialog(null, "Error al cargar los descuentos del empleado.");
            }
        }
    });
    }
    
    private void Contrato(){
        try{
            Connection cn = Conexion.conectar();
            String sql = "SELECT c.tipo_contrato FROM empleado e inner join tipoContrato c on e.id_tipoContrato = c.id_tipoContrato where e.Nombre_completo = '"+this.jComboBox_Empleados.getSelectedItem()+"'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                Contrato = rs.getString("c.tipo_contrato");
            }
            
        }catch(SQLException e){
            System.out.println("Error al obtener datos del empleado: "+e);
        }
    }
    
    private void Salario(String Cedula){
        try{
            Connection cn = Conexion.conectar();
            String sql = "SELECT salario from Devengados WHERE id_empleado ='"+Cedula+"'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                salario = Double.valueOf(rs.getString("salario"));
            }
            
        }catch(SQLException e){
            System.out.println("Error al obtener datos del empleado: "+e);
        }
    }
    
    private void Limpiar(){
        jComboBox_Empleados.setSelectedItem("Seleccione Empleado:");
        txtPension.setText("");
        txtSalud.setText("");
        txtCredito.setText("");
    }
    
    


}
