/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Conexion.Conexion;
import Controlador.Ctrl_Banco;
import Modelo.Banco;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class InterBancoEmpleado extends javax.swing.JInternalFrame {

    private String id_Cedula;
    private int id_banco;
    private String Nombre_banco;
    private String Numero_banco;
    private String Tipo;
    
    public InterBancoEmpleado() {
        initComponents();
        this.setSize(new Dimension(465, 400));
        this.setTitle("Informacion Bancaria");
        this.CargarComboEmpleados();
        this.DatosBanco();
        this.Cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_Cuenta = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_Empleados = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_Entidad = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtNumero_cuenta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Información Bancaria del Empleado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 410, 10));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Tipo de Cuenta:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 170, -1));

        jComboBox_Cuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Tipo de Cuenta:", "Cuenta de Ahorros (Electronico)", "Cuenta Corriente", " " }));
        getContentPane().add(jComboBox_Cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 160, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 410, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Seleccione el empleado:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 170, -1));

        jComboBox_Empleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Empleado:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 160, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Numero de Cuenta:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 170, -1));

        jComboBox_Entidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Entidad Bancaria:", "Alianza Fiduciaria", "Bancamia S.A", "Banco Agrario", "Banco Av Villas", "Banco Bbva Colombia S.A", "Banco Caja Social", "Banco Citibank", "Banco Coopcentral", "Banco Credifinanciera", "Banco Davivienda", "Banco De Bogota", "Banco De Occidente", "Banco Falabella", "Banco Finandina S.A. Bic", "Banco Gnb Sudameris", "Banco Itau", "Banco Mundo Mujer S.A.", "Banco Pichincha S.A", "Banco Popular", "Banco Procresit", "Banco Santander Colombia", "Banco Scotiabank Colpatria", "Banco Union Antes Giros", "Bancoomeva S.A.", "Bancolombia", "Cfa Cooperativa Financiera", "Coltefinanciera", "Confiar Cooperativa Financiera", "Coofinep Cooperativa Financiera", "Cotrafa", "Crezcamos S.A. Compañía De Financiamiento", "Dale", "Daviplata", "Iris", "Jfk Cooperativa Financiera", "Jp Morgan", "Lulo Bank", "Movii S.A.", "Nequi", "Nu. Colombia Compañia De Financiamiento S.A.", "Rappipay", "Rappipay Daviplata", "Ualá" }));
        getContentPane().add(jComboBox_Entidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 160, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Entidad Bancaria:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 170, -1));

        txtNumero_cuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumero_cuentaKeyTyped(evt);
            }
        });
        getContentPane().add(txtNumero_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 160, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 90, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumero_cuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero_cuentaKeyTyped
    char caracter = evt.getKeyChar();

    // Verificar si el carácter es un número, un punto o la tecla de retroceso
    boolean esNumero = (caracter >= '0' && caracter <= '9');
    boolean esPunto = (caracter == '.');
    boolean esBackspace = (caracter == KeyEvent.VK_BACK_SPACE);

    // Verificar si ya hay un punto en el texto
    boolean yaTienePunto = txtNumero_cuenta.getText().contains(".");

    // Si el carácter no es un número, no es un punto válido, no es backspace, o se supera la longitud máxima
    if (!esNumero && !(esPunto && !yaTienePunto) && !esBackspace) {
        evt.consume(); // Ignorar el carácter
    }
    }//GEN-LAST:event_txtNumero_cuentaKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Empleado = jComboBox_Empleados.getSelectedItem().toString();
        String Combo_entidad = jComboBox_Entidad.getSelectedItem().toString();
        String Combo_cuenta = jComboBox_Cuenta.getSelectedItem().toString();

        if (Empleado.equalsIgnoreCase("Seleccione Empleado:") ||
            Combo_entidad.equalsIgnoreCase("Seleccione Entidad Bancaria:") ||
            Combo_cuenta.equalsIgnoreCase("Seleccione Tipo de Cuenta:") ||
            txtNumero_cuenta.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Llene todos los campos obligatorios.");

        } else {
            this.DatosEmpleado(); // aquí se obtiene el id_Cedula correspondiente al empleado
            this.DatosBanco();
             
            Ctrl_Banco controlbanco = new Ctrl_Banco();

            // Validar si ya existe un banco registrado para este empleado
            if (controlbanco.ExisteBancoEmpleado(Empleado)) {
                JOptionPane.showMessageDialog(null, "Este empleado ya tiene información bancaria registrada.");
                return; // sale del proceso
            }

            Banco banco = new Banco();
            banco.setNombre_banco(Combo_entidad);
            banco.setTipo_cuenta(Combo_cuenta);
            banco.setNumero_de_cuenta(txtNumero_cuenta.getText().trim());
            banco.setId_cedula(id_Cedula);

            if (controlbanco.guardar(banco)) {
                JOptionPane.showMessageDialog(null, "Información bancaria registrada con éxito!");
                this.Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar información bancaria.");
            }
}

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Empleado = jComboBox_Empleados.getSelectedItem().toString();
        String Combo_entidad = jComboBox_Entidad.getSelectedItem().toString();
        String Combo_cuenta = jComboBox_Cuenta.getSelectedItem().toString();
        this.DatosEmpleado(); // Para obtener id_Cedula
        this.DatosBanco();    // Para obtener id_banco

        
        if(Empleado.equalsIgnoreCase("Seleccione Empleado:") || Combo_entidad.equalsIgnoreCase("Seleccione Entidad Bancaria:") || Combo_cuenta.equalsIgnoreCase("Seleccione Tipo de Cuenta:")
                || txtNumero_cuenta.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Llene todos los campos obligatorios.");
        }else{
            Banco banco = new Banco();
            Ctrl_Banco controlbanco = new Ctrl_Banco();
            
            banco.setNombre_banco(Combo_entidad);
            banco.setTipo_cuenta(Combo_cuenta);
            banco.setNumero_de_cuenta(txtNumero_cuenta.getText().trim());
            
            if(controlbanco.actualizar(banco, id_banco)){
                JOptionPane.showMessageDialog(null, "Información bancaria actualzida con éxito!");
                this.Limpiar();
            } else{
                JOptionPane.showMessageDialog(null, "Error al actualizar informacion bancaria.");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox_Cuenta;
    private javax.swing.JComboBox<String> jComboBox_Empleados;
    private javax.swing.JComboBox<String> jComboBox_Entidad;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtNumero_cuenta;
    // End of variables declaration//GEN-END:variables

    private void DatosEmpleado(){
        try{
            Connection cn = Conexion.conectar();
            String sql = "SELECT * FROM empleado WHERE Nombre_completo = '"+this.jComboBox_Empleados.getSelectedItem()+"'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                id_Cedula = rs.getString("cedula");
                
            }
            
        }catch(SQLException e){
            System.out.println("Error al obtener datos del empleado: "+e);
        }
    }
    
    private void DatosBanco(){
        try{
            Connection cn = Conexion.conectar();
            String sql = "SELECT * FROM banco b inner join empleado e on b.id_cedula = e.cedula where e.Nombre_completo = '"+this.jComboBox_Empleados.getSelectedItem()+"'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                id_banco = rs.getInt("b.id_banco");
                Nombre_banco = rs.getString("b.Nombre_banco");
                Numero_banco = rs.getString("b.Numero_de_cuenta");
                Tipo = rs.getString("b.Tipo_cuenta");
                
            }
            
        }catch(SQLException e){
            System.out.println("Error al obtener datos del empleado: "+e);
        }
    }
    
    private void CargarComboEmpleados(){
        Connection cn = Conexion.conectar();
        String sql = "SELECT * FROM empleado";
        
        Statement st;
        
        try{
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            jComboBox_Empleados.removeAllItems();
            jComboBox_Empleados.addItem("Seleccione Empleado:");
            while(rs.next()){
                jComboBox_Empleados.addItem(rs.getString("Nombre_completo"));
            }
            cn.close();
            
        }catch(SQLException e){
            System.out.println("Error al cargar Empleados"+e);
        }
    }
    
    private void Cargar() {
    jComboBox_Empleados.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String nombreEmpleado = jComboBox_Empleados.getSelectedItem().toString();

            // Evita ejecutar si está en la opción por defecto
            if (nombreEmpleado.equalsIgnoreCase("Seleccione Empleado:")) {
                return;
            }

            try {
                Connection cn = Conexion.conectar();
                String sql = "SELECT b.id_banco, b.Nombre_banco, b.Tipo_cuenta, b.Numero_de_cuenta " +
                             "FROM banco b " +
                             "INNER JOIN empleado e ON b.id_cedula = e.cedula " +
                             "WHERE e.Nombre_completo = ?";
                
                PreparedStatement pst = cn.prepareStatement(sql);
                pst.setString(1, nombreEmpleado);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    // Si encuentra datos, los carga en los campos
                    jComboBox_Entidad.setSelectedItem(rs.getString("Nombre_banco"));
                    jComboBox_Cuenta.setSelectedItem(rs.getString("Tipo_cuenta"));
                    txtNumero_cuenta.setText(rs.getString("Numero_de_cuenta"));

                    // Asigna el id_banco también
                    id_banco = rs.getInt("id_banco");
                } else {
                    // Si no hay relación en la tabla banco, limpia los campos
                    jComboBox_Entidad.setSelectedIndex(0); // "Seleccione Entidad:"
                    jComboBox_Cuenta.setSelectedIndex(0);  // "Seleccione Tipo de Cuenta:"
                    txtNumero_cuenta.setText("");

                    // Resetea id_banco a 0 por si acaso
                    id_banco = 0;
                }

                cn.close();
            } catch (SQLException ex) {
                System.out.println("Error al cargar datos bancarios: " + ex);
            }
        }
    });
}

    
    public void Limpiar(){
        jComboBox_Empleados.setSelectedItem("Seleccione Empleado:");
        jComboBox_Entidad.setSelectedItem("Seleccione Entidad Bancaria:");
        jComboBox_Cuenta.setSelectedItem("Seleccione Tipo de Cuenta:");
        txtNumero_cuenta.setText("");
    }
    
    

}
