package Vista;

import Conexion.Conexion;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author LENOVO
 */
public class InterGraficaDevengados extends javax.swing.JInternalFrame {

    String cedula;
    
    public InterGraficaDevengados() {
        initComponents();
        this.setSize(new Dimension(695, 460));
        this.setTitle("Grafica Total Devengados");
        this.CargarComboEmpleados();
        jComboBox_Empleados.addActionListener(evt -> {
        if (jComboBox_Empleados.getSelectedIndex() > 0) { // evitar "Seleccione Empleado"
            DatosEmpleado(); // obtiene la cédula
            cargarGraficaDevengado(); // genera la gráfica
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_Empleados = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Grafica Total Devengado Empleados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 660, 290));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Empleado:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        jComboBox_Empleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Empleado:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_Empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_Empleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void CargarComboEmpleados(){
        Connection cn = Conexion.conectar();
        String sql = "SELECT Nombre_completo FROM empleado";
        
        Statement st;
        
        try{
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            jComboBox_Empleados.removeAllItems();
            jComboBox_Empleados.addItem("Seleccione Empleado:");
            while(rs.next()){
                jComboBox_Empleados.addItem(rs.getString("Nombre_completo"));
            }
            cn.close();
  
        }catch(SQLException e){
            System.out.println("Error al cargar Empleados"+e);
        }   
    }
    
    private void DatosEmpleado(){
        try{
            Connection cn = Conexion.conectar();
            String sql = "SELECT * FROM empleado WHERE Nombre_completo = '"+this.jComboBox_Empleados.getSelectedItem()+"'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                cedula = rs.getString("cedula");
            }
            
        }catch(SQLException e){
            System.out.println("Error al obtener datos del empleado: "+e);
        }
    }
    
    private void cargarGraficaDevengado() {
        Connection cn = Conexion.conectar();
        String sql = "SELECT salario, Sub_transporte, Gastos_representativos, Viaticos, Comisiones, " +
                     "Horas_extra_diurnas, Horas_extra_nocturnas, Horas_extra_dominicales_diurnas, Horas_extra_dominicales_nocturnas " +
                     "FROM devengados WHERE id_empleado = ?";

        try (PreparedStatement pst = cn.prepareStatement(sql)) {
            pst.setString(1, cedula);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                DefaultPieDataset data = new DefaultPieDataset();

                long salario = rs.getLong("salario");
                long transporte = rs.getLong("Sub_transporte");
                long gastos = rs.getLong("Gastos_representativos");
                long viaticos = rs.getLong("Viaticos");
                long comisiones = rs.getLong("Comisiones");
                long h1 = rs.getLong("Horas_extra_diurnas");
                long h2 = rs.getLong("Horas_extra_nocturnas");
                long h3 = rs.getLong("Horas_extra_dominicales_diurnas");
                long h4 = rs.getLong("Horas_extra_dominicales_nocturnas");

                if (salario > 0) data.setValue("Salario", salario);
                if (transporte > 0) data.setValue("Sub. Transporte", transporte);
                if (gastos > 0) data.setValue("Gastos Rep.", gastos);
                if (viaticos > 0) data.setValue("Viáticos", viaticos);
                if (comisiones > 0) data.setValue("Comisiones", comisiones);
                if (h1 > 0) data.setValue("H. Extra Diurna", h1);
                if (h2 > 0) data.setValue("H. Extra Nocturna", h2);
                if (h3 > 0) data.setValue("H. Dom. Diurna", h3);
                if (h4 > 0) data.setValue("H. Dom. Nocturna", h4);

                JFreeChart chart = ChartFactory.createPieChart(
                    "Composición Devengado",
                    data,
                    true,
                    true,
                    false
                );

                // Mostrar etiquetas con nombre y valor (formato: "Etiqueta: $valor")
                PiePlot plot = (PiePlot) chart.getPlot();
                plot.setLabelGenerator(new StandardPieSectionLabelGenerator(
                    "{0}: ${1} ({2})", 
                    new DecimalFormat("###,###"), // valor
                    new DecimalFormat("0.00%")    // porcentaje
                ));


                ChartPanel panel = new ChartPanel(chart);
                panel.setMouseWheelEnabled(true);
                panel.setPreferredSize(new Dimension(jPanel1.getWidth(), jPanel1.getHeight()));

                jPanel1.removeAll();
                jPanel1.setLayout(new java.awt.BorderLayout());
                jPanel1.add(panel, java.awt.BorderLayout.CENTER);
                jPanel1.revalidate();
                jPanel1.repaint();

            } else {
                JOptionPane.showMessageDialog(this, "No hay datos de devengado para este empleado.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar gráfica: " + e.getMessage());
        }
}

}
