/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Conexion.Conexion;
import Controlador.Ctrl_Empleado;
import Modelo.Empleado;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class InterAgregarEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterAgregarEmpleado
     */
    public InterAgregarEmpleado() {
        initComponents();
        this.setSize(new Dimension(1220, 585));
        this.setTitle("Agregar Empleado");
        this.CargarTablaEmpleados();
        this.CargarComboCargo();
        this.CargarComboDepartamento();
        this.CargarComboContrato();
    }
    
    String idEmpleado = "";
    int idCargo = 0;
    int idDepartamento = 0;
    int idContrato = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre_Empleado = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jDate_Ingreso = new com.toedter.calendar.JDateChooser();
        jDate_Retiro = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_Contrato = new javax.swing.JComboBox<>();
        jComboBox_Cargo = new javax.swing.JComboBox<>();
        jComboBox_Departamento = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Empleado = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Agregar Nuevo Empleado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Fecha de Retiro (Opcional):");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Tipo de contrato:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 190, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Cedula del empleado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Telefono:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 150, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Fecha de Ingreso:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 150, -1));
        getContentPane().add(txtNombre_Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 160, -1));

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 160, -1));

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 160, -1));
        getContentPane().add(jDate_Ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 160, -1));
        getContentPane().add(jDate_Retiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 160, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Nombre del empleado:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 160, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Tipo de Cargo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 160, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Departamento de trabajo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 190, -1));

        jComboBox_Contrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione tipo de Contrato:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_Contrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 160, -1));

        jComboBox_Cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Cargo:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_Cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 160, -1));

        jComboBox_Departamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Departamento de trabajo:", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox_Departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 160, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 910, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 410, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 910, 10));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Guardar Empleado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Actualizar Empleado");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, -1, -1));

        jTable_Empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Empleado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 710, 360));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Despedir Empleado");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
    char caracter = evt.getKeyChar();

    // Verificar si el carácter es un número, un punto o la tecla de retroceso
    boolean esNumero = (caracter >= '0' && caracter <= '9');
    boolean esPunto = (caracter == '.');
    boolean esBackspace = (caracter == KeyEvent.VK_BACK_SPACE);

    // Verificar si ya hay un punto en el texto
    boolean yaTienePunto = txtCedula.getText().contains(".");

    // Si el carácter no es un número, no es un punto válido, no es backspace, o se supera la longitud máxima
    if (!esNumero && !(esPunto && !yaTienePunto) && !esBackspace) {
        evt.consume(); // Ignorar el carácter
    }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
    char caracter = evt.getKeyChar();

    // Verificar si el carácter es un número, un punto o la tecla de retroceso
    boolean esNumero = (caracter >= '0' && caracter <= '9');
    boolean esPunto = (caracter == '.');
    boolean esBackspace = (caracter == KeyEvent.VK_BACK_SPACE);

    // Verificar si ya hay un punto en el texto
        boolean yaTienePunto = txtTelefono.getText().contains(".");

    // Si el carácter no es un número, no es un punto válido, no es backspace, o se supera la longitud máxima
    if (!esNumero && !(esPunto && !yaTienePunto) && !esBackspace) {
        evt.consume(); // Ignorar el carácter
    }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Obtener valores seleccionados de los ComboBox
        String comboCargo = jComboBox_Cargo.getSelectedItem().toString();
        String comboDepartamento = jComboBox_Departamento.getSelectedItem().toString();
        String comboContrato = jComboBox_Contrato.getSelectedItem().toString();

        // Validación de campos obligatorios
        if (txtCedula.getText().trim().isEmpty() ||
            txtNombre_Empleado.getText().trim().isEmpty() ||
            txtTelefono.getText().trim().isEmpty() ||
            jDate_Ingreso.getDate() == null ||
            comboCargo.equalsIgnoreCase("Seleccione Cargo:") ||
            comboDepartamento.equalsIgnoreCase("Seleccione Departamento de trabajo:") ||
            comboContrato.equalsIgnoreCase("Seleccione Tipo de contrato:")) {

            JOptionPane.showMessageDialog(null, "Llene todos los campos obligatorios.");
            return;
        }

        // Validar que la cédula sea un número
        if (!txtCedula.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "La cédula debe contener solo números.");
            return;
        }

        // Validar si la cédula ya está registrada
        Ctrl_Empleado controlempleado = new Ctrl_Empleado();
        if (controlempleado.ExisteEmpleadoPorCedula(txtCedula.getText().trim())) {
            JOptionPane.showMessageDialog(null, "Ya existe un empleado registrado con esta cédula.");
            return;
        }

        // Obtener IDs relacionados antes de guardar (puede que actualicen idCargo, idDepartamento, idContrato)
        this.DatosCargo();
        this.DatosDepartamento();
        this.DatosContrato();

        // Crear y llenar objeto Empleado
        Empleado empleado = new Empleado();
        empleado.setCedula(txtCedula.getText());
        empleado.setNombre_completo(txtNombre_Empleado.getText().trim());

        // Fecha de ingreso
        Date fechaIngreso = jDate_Ingreso.getDate();
        java.sql.Date fechaIngresoSQL = new java.sql.Date(fechaIngreso.getTime());
        empleado.setFecha_ingreso(fechaIngresoSQL.toString());

        // Fecha de retiro (opcional)
        Date fechaRetiro = jDate_Retiro.getDate();
        if (fechaRetiro != null) {
            java.sql.Date fechaRetiroSQL = new java.sql.Date(fechaRetiro.getTime());
            empleado.setFecha_retiro(fechaRetiroSQL.toString());
        } else {
            empleado.setFecha_retiro(null); // o una cadena vacía, según tu base de datos
        }

        // Resto de datos
        empleado.setTelefono(txtTelefono.getText().trim());
        empleado.setId_cargo(idCargo);
        empleado.setId_departamento(idDepartamento);
        empleado.setId_tipoContrato(idContrato);

        // Guardar empleado
        if (controlempleado.guardar(empleado)) {
            JOptionPane.showMessageDialog(null, "Empleado registrado con éxito!");
        } else {
            JOptionPane.showMessageDialog(null, "Error al guardar empleado.");
        }
        
        this.CargarTablaEmpleados();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Obtener valores seleccionados de los ComboBox
        String comboCargo = jComboBox_Cargo.getSelectedItem().toString();
        String comboDepartamento = jComboBox_Departamento.getSelectedItem().toString();
        String comboContrato = jComboBox_Contrato.getSelectedItem().toString();

        // Validación de campos obligatorios
        if (txtCedula.getText().trim().isEmpty() ||
            txtNombre_Empleado.getText().trim().isEmpty() ||
            txtTelefono.getText().trim().isEmpty() ||
            jDate_Ingreso.getDate() == null ||
            comboCargo.equalsIgnoreCase("Seleccione Cargo:") ||
            comboDepartamento.equalsIgnoreCase("Seleccione Departamento de trabajo:") ||
            comboContrato.equalsIgnoreCase("Seleccione Tipo de contrato:")) {

            JOptionPane.showMessageDialog(null, "Llene todos los campos obligatorios.");
            return;
        }

        // Validar que la cédula sea un número
        if (!txtCedula.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "La cédula debe contener solo números.");
            return;
        }
        
        this.DatosCargo();
        this.DatosDepartamento();
        this.DatosContrato();
        
        Ctrl_Empleado controlempleado = new Ctrl_Empleado();
        
        // Crear y llenar objeto Empleado
        Empleado empleado = new Empleado();
        idEmpleado = txtCedula.getText().trim();
        
        empleado.setNombre_completo(txtNombre_Empleado.getText().trim());
        
        Date fechaIngreso = jDate_Ingreso.getDate();
        java.sql.Date fechaIngresoSQL = new java.sql.Date(fechaIngreso.getTime());
        empleado.setFecha_ingreso(fechaIngresoSQL.toString());
        
        // Fecha de retiro (opcional)
        Date fechaRetiro = jDate_Retiro.getDate();
        if (fechaRetiro != null) {
            java.sql.Date fechaRetiroSQL = new java.sql.Date(fechaRetiro.getTime());
            empleado.setFecha_retiro(fechaRetiroSQL.toString());
        } else {
            empleado.setFecha_retiro(null); // o una cadena vacía, según tu base de datos
        }

        empleado.setTelefono(txtTelefono.getText().trim());
        empleado.setId_cargo(idCargo);
        empleado.setId_departamento(idDepartamento);
        empleado.setId_tipoContrato(idContrato);
        
        if (controlempleado.actualizar_Completo(empleado, idEmpleado)) {
            JOptionPane.showMessageDialog(null, "Empleado actualizado con éxito!");
        } else {
            JOptionPane.showMessageDialog(null, "Error al actualizar empleado.");
        }
        
        this.CargarTablaEmpleados();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Obtener valores seleccionados de los ComboBox
        String comboCargo = jComboBox_Cargo.getSelectedItem().toString();
        String comboDepartamento = jComboBox_Departamento.getSelectedItem().toString();
        String comboContrato = jComboBox_Contrato.getSelectedItem().toString();

        // Validación de campos obligatorios
        if (txtCedula.getText().trim().isEmpty() ||
            txtNombre_Empleado.getText().trim().isEmpty() ||
            txtTelefono.getText().trim().isEmpty() ||
            jDate_Ingreso.getDate() == null ||
            comboCargo.equalsIgnoreCase("Seleccione Cargo:") ||
            comboDepartamento.equalsIgnoreCase("Seleccione Departamento de trabajo:") ||
            comboContrato.equalsIgnoreCase("Seleccione Tipo de contrato:")) {

            JOptionPane.showMessageDialog(null, "Llene todos los campos obligatorios.");
            return;
        }
        
        // Validar que la cédula sea un número
        if (!txtCedula.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "La cédula debe contener solo números.");
            return;
        }

        // Validar si la cédula ya está registrada
        Ctrl_Empleado controlempleado = new Ctrl_Empleado();
        
        idEmpleado = txtCedula.getText().trim();

        // Crear y llenar objeto Empleado
        Empleado empleado = new Empleado();
       
        java.sql.Date fechaActualSQL = new java.sql.Date(System.currentTimeMillis());
        empleado.setFecha_retiro(fechaActualSQL.toString());

        if (controlempleado.actualizar_Fecha(empleado, idEmpleado)) {
            JOptionPane.showMessageDialog(null, "Empleado actualizado con éxito!");
        } else {
            JOptionPane.showMessageDialog(null, "Error al guardar empleado.");
        }    
        this.CargarTablaEmpleados();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox_Cargo;
    private javax.swing.JComboBox<String> jComboBox_Contrato;
    private javax.swing.JComboBox<String> jComboBox_Departamento;
    private com.toedter.calendar.JDateChooser jDate_Ingreso;
    private com.toedter.calendar.JDateChooser jDate_Retiro;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public static javax.swing.JTable jTable_Empleado;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre_Empleado;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void CargarComboCargo(){
        Connection cn = Conexion.conectar();
        String sql = "SELECT * FROM cargo";
        
        Statement st;
        
        try{
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            jComboBox_Cargo.removeAllItems();
            jComboBox_Cargo.addItem("Seleccione Cargo:");
            while(rs.next()){
                jComboBox_Cargo.addItem(rs.getString("Nombre_cargo"));
            }
            cn.close();
            
        }catch(SQLException e){
            System.out.println("Error al cargar cargo"+e);
        }
        
    }
    
    private void CargarComboDepartamento(){
        Connection cn = Conexion.conectar();
        String sql = "SELECT * FROM departamento";
        
        Statement st;
        
        try{
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            jComboBox_Departamento.removeAllItems();
            jComboBox_Departamento.addItem("Seleccione Departamento de trabajo:");
            while(rs.next()){
                jComboBox_Departamento.addItem(rs.getString("Nombre_departamento"));
            }
            cn.close();
            
        }catch(SQLException e){
            System.out.println("Error al cargar departamento"+e);
        }
        
    }
    
    private void CargarComboContrato(){
        Connection cn = Conexion.conectar();
        String sql = "SELECT * FROM tipoContrato";
        
        Statement st;
        
        try{
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            jComboBox_Contrato.removeAllItems();
            jComboBox_Contrato.addItem("Seleccione tipo de Contrato:");
            while(rs.next()){
                jComboBox_Contrato.addItem(rs.getString("tipo_contrato"));
            }
            cn.close();
            
        }catch(SQLException e){
            System.out.println("Error al cargar departamento"+e);
        }
        
    }

    
    private void DatosCargo(){
        try{
            Connection cn = Conexion.conectar();
            String sql = "SELECT id_cargo FROM cargo WHERE Nombre_cargo = '"+this.jComboBox_Cargo.getSelectedItem()+"'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                idCargo = rs.getInt("id_cargo");
                
            }
            
        }catch(SQLException e){
            System.out.println("Error al obtener datos del cargo: "+e);
        }


    }
    
    private void DatosDepartamento(){
        try{
            Connection cn = Conexion.conectar();
            String sql = "SELECT id_departamento FROM departamento WHERE Nombre_departamento = '"+this.jComboBox_Departamento.getSelectedItem()+"'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                idDepartamento = rs.getInt("id_departamento");
                
            }
            
        }catch(SQLException e){
            System.out.println("Error al obtener datos del cargo: "+e);
        }


    }
    
    private void DatosContrato(){
        try{
            Connection cn = Conexion.conectar();
            String sql = "SELECT id_tipoContrato FROM tipoContrato WHERE tipo_contrato = '"+this.jComboBox_Contrato.getSelectedItem()+"'";
            Statement st;
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                idContrato = rs.getInt("id_tipoContrato");
                
            }
            
        }catch(SQLException e){
            System.out.println("Error al obtener datos del cargo: "+e);
        }


    }
    
    private void CargarTablaEmpleados() {
        Connection cn = Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "SELECT cedula,Nombre_Completo,telefono,fecha_ingreso,fecha_retiro,Nombre_cargo AS Cargo,Nombre_departamento AS Departamento, tipo_contrato AS Contrato FROM empleado e\n" +
                    "INNER JOIN cargo c on e.id_cargo = c.id_cargo\n" +
                    "INNER JOIN departamento d on d.id_departamento = e.id_departamento\n" +
                    "INNER JOIN tipoContrato t on t.id_tipoContrato = e.id_tipoContrato;;";
        Statement st;

        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            InterAgregarEmpleado.jTable_Empleado = new JTable(model);
            InterAgregarEmpleado.jScrollPane1.setViewportView(InterAgregarEmpleado.jTable_Empleado);

            model.addColumn("Cedula");
            model.addColumn("Nombre_Completo");
            model.addColumn("Telefono");
            model.addColumn("Fecha_ingreso");
            model.addColumn("Fecha_retiro");
            model.addColumn("Cargo");
            model.addColumn("Departamento");
            model.addColumn("Contrato");

            while (rs.next()) {
                Object fila[] = new Object[8];

                for (int i = 0; i < 8; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al llenar la tabla Cliente " + e);
        }

        jTable_Empleado.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_Empleado.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idEmpleado = String.valueOf(model.getValueAt(fila_point, columna_point));
                    EnviarDatosClienteSeleccionadas(idEmpleado);
                }

            }
        });
    }

    private void EnviarDatosClienteSeleccionadas(String idCliente) {
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement( "SELECT cedula,Nombre_Completo,telefono,fecha_ingreso,fecha_retiro,Nombre_cargo AS Cargo,Nombre_departamento AS Departamento,"+
                    "tipo_contrato AS contrato FROM empleado e\n" +
                    "INNER JOIN cargo c on e.id_cargo = c.id_cargo\n" +
                    "INNER JOIN departamento d on d.id_departamento = e.id_departamento\n" +
                    "INNER JOIN tipoContrato t on t.id_tipoContrato = e.id_tipoContrato "
                    + "where cedula = '" + idCliente + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txtCedula.setText(rs.getString("cedula"));
                txtNombre_Empleado.setText(rs.getString("Nombre_Completo"));
                txtTelefono.setText(rs.getString("telefono"));
                jDate_Ingreso.setDate(rs.getDate("fecha_ingreso"));
                jDate_Retiro.setDate(rs.getDate("fecha_retiro"));
                jComboBox_Cargo.setSelectedItem(rs.getString("Cargo"));
                jComboBox_Departamento.setSelectedItem(rs.getString("Departamento"));
                jComboBox_Contrato.setSelectedItem(rs.getString("Contrato"));
            }
            cn.close();
        } catch (SQLException e) {
            System.out.println("Error al seleccionar Cliente: " + e);
        }
    }
    
    
}
